# Given: A DNA string s of length at most 1000 nt.

# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

# Sample Dataset

# AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
# Sample Output

# 20 12 17 21

s = 'AGCGTACTAATGTAGAGTATTTAAGATCTGGCCTGAGAACTAAACTTATGATGAGGTCGAACCCCTGAGGCGCTTCCATTCTTCCCACAGCGTACTACCTCCCATCATCTATTACTGTAGAGCGTGATGAGAGACACAAGAAAGGGCAGGCGGTTTTTGCGCGATCGTCGTTGTTGAACTAATTCGCTAGTTTGCTGAGGATGATAGACATCGGTGCACAGTTTACACTAAAAGAATACTAAATGAGGGTGTGGGTGAACCCAGGTAAACATAACTTGTGAATGTCTTGAACCCACGAGGCCAAGCAACTTCTTCGATATTCGTGACGAACAGTACTAGTAACAGAGCTCCGTATTGCGCATACTTGTCAAGCGGCCATATTCTCTATCGTGGGTCCGATTGCAATGACCTAGCCTCGGCGATAAGCCATGCCGAAACAGCAACCCTTAGTCCATGGTGGGACCGCGATGTGAGACATCCGAAGTAGTGTCGGAATACTTGAAAGAAGGCCCATAAAGAACATCAATCTGCAGAGAATCTTCCTCCCACACTTCAGGTTCATTCTACTTAACGTATCGCGTGGGGGCGTCCACGGTGCAACGCGGTGGTTTTCCATGTGCTGATTATAGTTAATTGCGATTCAGGGCTACGTCTTTGATCCTATAGCGAACACATGATGTAAGAGTGATTAAGAATTATAACGCCGAGGCATGATATACAGATTCAGTAGTAATCGGATGTTGTCAGTGACAGGCCAGCTACCAACGTCCCCAGGAGAGGAATTTCTGTGAACGACATGTTTAGGGACACATTTGAATTGACACTCCCCAGGCCCTCGCGGAGGAGTTAGAGAGGTGTCATTGGTCGACTAGCCAAACTCTATATGGAGGCGATATTATGGGAAGGCGAGCGGAGTCCCATCCTTGCTCACAAAAGGGATTTGGCGTACACTAGAGTGGGAGTTTTATTTCTT'
acount = 0
ccount =0
gcount = 0
tcount = 0
for c in range(0, len(s)):
	if s[c] == "A":
		acount += 1
	elif s[c] == "C":
		ccount += 1
	elif s[c] == "G":
		gcount += 1
	else:
		tcount += 1
print acount, ccount, gcount, tcount

