# Given: A DNA string Text and an integer k.

# Return: All most frequent k-mers in Text (in any order).

# ACGTTGCATGTCGCATGATGCATGAGAGCT
# 4

# Output
# CATG GCAT


#f = open('rosalind_1a.txt', 'r')
f = open('frequent_words.txt', 'r')

c = 0
k = 0

#rosalind_1a.txt
for line in f:
    print c
    if c == 1:
        text = line
        print text
    elif c == 2:
        k = int(line) 
    c+=1;

text = "TGCAAACATGCAAACACCCGATCGGGGAAACTATGCAAACAGACAAGCCTTGGAAACTAGACAAGCCTTGGAAACTACCCGATCGGGACAAGCCTTGACAAGCCTTGGAAACTAAGTGCACGCAGTGCACGCAGTGCACGCGGAAACTAGACAAGCCTTTGCAAACATGCAAACAAGTGCACGCCCCGATCGGGACAAGCCTTTGCAAACACCCGATCGGGACAAGCCTTGGAAACTATGCAAACAAGTGCACGCGACAAGCCTTGACAAGCCTTTGCAAACAGGAAACTAGGAAACTAGACAAGCCTTGGAAACTAGGAAACTAGACAAGCCTTGACAAGCCTTTGCAAACAGGAAACTAAGTGCACGCGACAAGCCTTGGAAACTAGGAAACTAAGTGCACGCGACAAGCCTTGACAAGCCTTGACAAGCCTTAGTGCACGCGGAAACTATGCAAACAGACAAGCCTTTGCAAACAGGAAACTATGCAAACAAGTGCACGCTGCAAACAAGTGCACGCCCCGATCGGGACAAGCCTTTGCAAACACCCGATCGGAGTGCACGCGGAAACTAGGAAACTATGCAAACAGACAAGCCTTTGCAAACAAGTGCACGCGACAAGCCTTGACAAGCCTTGGAAACTAGGAAACTAGGAAACTAGACAAGCCTTGACAAGCCTTAGTGCACGCTGCAAACAAGTGCACGCAGTGCACGCGACAAGCCTTTGCAAACAGACAAGCCTTCCCGATCGGGACAAGCCTTGACAAGCCTTTGCAAACATGCAAACACCCGATCGGAGTGCACGCGACAAGCCTTGACAAGCCTTGACAAGCCTTCCCGATCGGAGTGCACGCGGAAACTAAGTGCACGCGACAAGCCTTAGTGCACGCCCCGATCGGCCCGATCGGAGTGCACGCGGAAACTATGCAAACA"
k = 14

#sample
#text = "CGGAAGCGAGATTCGCGTGGCGTGATTCCGGCGGGCGTGGAGAAGCGAGATTCATTCAAGCCGGGAGGCGTGGCGTGGCGTGGCGTGCGGATTCAAGCCGGCGGGCGTGATTCGAGCGGCGGATTCGAGATTCCGGGCGTGCGGGCGTGAAGCGCGTGGAGGAGGCGTGGCGTGCGGGAGGAGAAGCGAGAAGCCGGATTCAAGCAAGCATTCCGGCGGGAGATTCGCGTGGAGGCGTGGAGGCGTGGAGGCGTGCGGCGGGAGATTCAAGCCGGATTCGCGTGGAGAAGCGAGAAGCGCGTGCGGAAGCGAGGAGGAGAAGCATTCGCGTGATTCCGGGAGATTCAAGCATTCGCGTGCGGCGGGAGATTCAAGCGAGGAGGCGTGAAGCAAGCAAGCAAGCGCGTGGCGTGCGGCGGGAGAAGCAAGCGCGTGATTCGAGCGGGCGTGCGGAAGCGAGCGG"
#k = 12
    
length = len(text)
kmerlist = list([])
freqlist = list([])

freq = 0
maxFreq = 0
pos = 0

while pos < length - k + 2:
    
    freq = 1
    checkpos = pos + 1
    newkmer = str(text[pos : pos + k - 1])
    if newkmer not in kmerlist:
        
        while checkpos <= length - k + 1:
            if text[checkpos : checkpos + k - 1] == newkmer:
                freq += 1
            checkpos += 1

        if freq == maxFreq:
        
            kmerlist.append(newkmer)
            freqlist.append(freq)            
    
        elif freq > maxFreq:
            lcount = len(kmerlist)            
            del kmerlist[:]
            del freqlist[:]
                        
            #assert len(kmerlist) == 0, "List not empty"
        
            kmerlist.append(newkmer)
            freqlist.append(freq)
            maxFreq = freq
            
    pos += 1   
    
print(kmerlist)

