def patternCount(Text, Pattern):

    count = 0

    for i in range(0, len(Text) - len(Pattern) + 1):
        if Text[i:i + len(Pattern)] == Pattern:
            count += 1
    return count

def FrequentWords(Text, k):
    FrequentPatterns = set()
    Count = []
    for i in range(0, len(Text) - k):
        pattern = Text[i:i + k]        
        Count.append(patternCount(Text, pattern))
    maxCount = 0
    for val in Count:
        if val > maxCount:
            maxCount = val
           
    for j in range(0, len(Text) - k):
      if Count[j] == maxCount:
          FrequentPatterns.add(Text[j:j+k])
          

    #Count[i] stores Count(Text, Pattern) for Pattern = Text(i, k)
    print maxCount 
    return FrequentPatterns

freq = FrequentWords("CCGCTGACCGCTGATTAAAGAATCATTCTTTAAAGAATTAACTCTAGGAAGTTCATTCTTTAACTCTCCGCTGATCATTCTCCGCTGACCGCTGACCGCTGATCATTCTCCGCTGATCATTCTTCATTCTCCGCTGATCATTCTAGGAAGTTCATTCTCCGCTGATTAACTCTCCGCTGATCATTCTAGGAAGTAGGAAGTCCGCTGATTAAAGAATTAAAGAAAGGAAGTTTAAAGAATCATTCTTTAACTCTCCGCTGACCGCTGATTAACTCTCCGCTGACCGCTGAAGGAAGTAGGAAGTAGGAAGTTTAACTCTAGGAAGTTTAAAGAATCATTCTAGGAAGTCCGCTGATCATTCTCCGCTGACCGCTGAAGGAAGTTTAAAGAACCGCTGATCATTCTAGGAAGTAGGAAGTTCATTCTAGGAAGTTTAACTCTCCGCTGAAGGAAGTTTAACTCTTTAAAGAACCGCTGATTAAAGAAAGGAAGTCCGCTGATTAACTCTAGGAAGTTCATTCTAGGAAGTTTAAAGAACCGCTGATTAACTCTTCATTCTCCGCTGATCATTCTTTAACTCTCCGCTGATTAACTCTTTAAAGAATTAAAGAATCATTCTTCATTCTAGGAAGTTCATTCTTCATTCTTCATTCTTCATTCTAGGAAGTTCATTCTAGGAAGTCCGCTGATCATTCTCCGCTGATTAAAGAATTAACTCTAGGAAGTCCGCTGATTAACTCTCCGCTGATTAAAGAAAGGAAGTTTAAAGAACCGCTGAAGGAAGTAGGAAGTTTAAAGAA", 13)
print freq



